### ISSUE TITLE
쌍대 정리 관련한 글에서

### ISSUE THREAD

**Issue by kwhkim** [metamath1/ml-simple-works#1]
오류를 발견한 듯 하여 남겨드립니다.

Hx(x∗,v∗)가 양정이므로 (x∗,v∗)에서 충분히 가까운 (x,v)에서의 헤시안 Hx(x,v)도 양정이다. 이 부분에 대해 엄밀한 증명을 위해서는 해석학이 필요하나 여기서는 함수 f(x)가 양수이면 x에서 아주 약간 떨어진 근방에서도 양수라는 정도로 이해하고 넘어가기로 한다. 예를 들어 f(x)=3x2−5의 2계 미분은 f′′(x)=6x인데 f(x)의 아래로 볼록한 점 x∗=5/3−−−√에서 f′′(x∗)>0임이 분명하다. 또한 x∗에서 약간 떨어진 어떤 임의의 x에 대해서도 f′′(x)>0가 됨을 알 수 있다. 하지만 x가 x∗에서 멀리 떨어져서 x<0인 영역으로 가게 되면 f′′(x)<0이 된다. 즉 f′′(x)가 x∗ 근처에서 국부적으로 양수인것이다.

에서 3x^2-5의 1계 미분이 6x이고 2계 미분이 6이므로 항상 양수입니다. 예를 들려면 3차 다항식을 쓰시는데.. 나을 듯 합니다...

**Comment by metamath1** [comment]
네 예가 적절치 못했네요 제가 이걸 왜 2차 다항식으로 작성한지 오래되서 기억이 나지 않네요. 아마 f'(x)=3x^2-5라고 쓰고 싶었던것 같습니다. 적절한 3차 다항식으로 예를 수정하도록 하거나 3x^2-5를 적분하여 예를 바꾸도록 하겠습니다.
